### PR TITLE
mb-name

### PR DESCRIPTION
**Pull request by mrburns20**
I don't think I'm doing this right

### CODE REVIEW

**Comment by ArchdukeTim** [comment]
You did it perfectly.

**Comment by mrburns20** [comment]
Oh great, I was just confused that there were fewer pull requests than names, and most of them were about years.

**Comment by ArchdukeTim** [comment]
Now commit again adding what year you are and with a new commit message describing that change

**Comment by ArchdukeTim** [comment]
Yeah we did an exercise in class that added the names

**Review by ArchdukeTim — APPROVED** [review]

**Pull request merged**
