### PR TITLE
This will add my year jb

### PR DESCRIPTION
**Pull request by Jrbartone**

### CODE REVIEW

**Comment by ArchdukeTim** [comment]
Hmm so it looks like you had a merge conflict when pulling. Try pulling from the master and re-branching. Ideally the only commit is the one you create, and no merge commits

**Comment by Jrbartone** [comment]
Ok- I looked into it- 
So for some reason the default commit comment said there's a conflict with master but I'm not sure if there actually is one

**Comment by ArchdukeTim** [comment]
There's not. So what I'd like you to do is edit the commit message. You can do that by amending the commit. See if you can google how to do that in IntelliJ

**Comment by Jrbartone** [comment]
Should be good now- fixed in intelliJ

**Review by ArchdukeTim — APPROVED** [review]
Interesting that there's still that merge commit...we can fix that later

**Review by LeoTheMighty — APPROVED** [review]

**Pull request merged**
